export const metadata = {
  title: "Dev Dairy - Support",
  description: "Generated by create next app",
};

const SupportPage = () => {
  return (
    <div className="max-w-5xl mx-auto p-6 flex flex-col items-center justify-center min-h-screen">
      <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-6">
        Support Center 🛠️
      </h1>

      <p className="text-gray-600 dark:text-gray-300 mb-10 text-center max-w-xl">
        Need help? Check out common issues or contact our support team.
      </p>

      <div className="grid md:grid-cols-2 gap-6 w-full">
        <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow-md">
          <h3 className="text-xl font-semibold mb-2 text-gray-900 dark:text-white">
            💡 FAQs
          </h3>
          <p className="text-gray-600 dark:text-gray-300 text-sm">
            Find answers to the most common questions about our platform.
          </p>
        </div>

        <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow-md">
          <h3 className="text-xl font-semibold mb-2 text-gray-900 dark:text-white">
            📞 Contact Support
          </h3>
          <p className="text-gray-600 dark:text-gray-300 text-sm">
            Reach out to our support team for any issues or help.
          </p>
        </div>

        <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow-md">
          <h3 className="text-xl font-semibold mb-2 text-gray-900 dark:text-white">
            ⚙️ Technical Help
          </h3>
          <p className="text-gray-600 dark:text-gray-300 text-sm">
            Facing technical issues? Get step-by-step assistance here.
          </p>
        </div>

        <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow-md">
          <h3 className="text-xl font-semibold mb-2 text-gray-900 dark:text-white">
            📚 Documentation
          </h3>
          <p className="text-gray-600 dark:text-gray-300 text-sm">
            Explore detailed guides and documentation.
          </p>
        </div>
      </div>
    </div>
  );
};

export default SupportPage;
