import Image from "next/image";
import kathBirali from "../../assets/images/kathBirali.jpg";

export const metadata = {
  title: "Dev Dairy - About",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <div className="max-w-6xl mx-auto grid md:grid-cols-2 gap-10 items-center p-6 mt-29">
      {/* Left Side */}
      <div>
        <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-4">
          About Me
        </h1>

        <p className="text-gray-600 dark:text-gray-300 mb-4">
          Hi, I am Saharier Omi. A passionate web developer who loves building
          modern and responsive web applications. I am currently learning and
          working with technologies like React, Next.js, and Tailwind CSS.
        </p>

        <p className="text-gray-600 dark:text-gray-300 mb-4">
          My goal is to become a full-stack developer and create impactful
          digital experiences. I enjoy solving problems, learning new
          technologies, and sharing my knowledge through blogs.
        </p>

        <p className="text-gray-600 dark:text-gray-300">
          This blog is a place where I document my learning journey and help
          others grow in web development.
        </p>
      </div>

      {/* Right Side */}
      <div className="flex justify-center">
        <Image
          src={kathBirali}
          alt="About Image"
          width={400}
          height={400}
          className="rounded-xl"
        />
      </div>
    </div>
  );
};

export default AboutPage;
