import Link from "next/link";

export const metadata = {
  title: "Dev Dairy - Contact",
  description: "Generated by create next app",
};


const ContactPage = () => {
  return (
    <div className="max-w-5xl mx-auto p-6 flex flex-col items-center justify-center min-h-screen">
      <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-6">
        Contact Us 📩
      </h1>

      <p className="text-gray-600 dark:text-gray-300 mb-6 text-center max-w-xl">
        Have any questions? You can contact us or visit our support center for
        help.
      </p>

      {/* 🔥 Support Button */}
      <Link href="/contact/support">
        <button className="mb-8 bg-gray-900 hover:bg-gray-700 text-white px-6 py-2 rounded-lg transition">
          Go to Support Center
        </button>
      </Link>

      {/* Form */}
      <form className="w-full max-w-xl bg-white dark:bg-gray-800 p-6 rounded-xl shadow-md space-y-4">
        <input
          type="text"
          placeholder="Your Name"
          className="w-full p-3 rounded-lg border"
        />
        <input
          type="email"
          placeholder="Your Email"
          className="w-full p-3 rounded-lg border"
        />
        <textarea
          rows="4"
          placeholder="Your Message"
          className="w-full p-3 rounded-lg border"
        ></textarea>

        <button
          type="submit"
          className="w-full bg-yellow-400 hover:bg-yellow-500 text-black py-3 rounded-lg"
        >
          Send Message
        </button>
      </form>
    </div>
  );
};

export default ContactPage;
