import Link from "next/link";

export const metadata = {
  title: "Dev Dairy - Profile",
  description: "Generated by create next app",
};

const ProfilePage = () => {
  return (
    <div className="w-full max-w-4xl mx-auto">
      {/* Profile Card */}
      <div className="bg-white dark:bg-gray-800 rounded-xl shadow p-6 mb-6 flex flex-col items-center text-center">
        <div className="w-24 h-24 rounded-full bg-gray-300 mb-4">
          <p></p>
        </div>

        <h2 className="text-2xl font-bold text-gray-900 dark:text-white">
          Saharier Omi
        </h2>

        <p className="text-gray-500 mb-2">@saharieromi</p>

        <p className="text-gray-600 dark:text-gray-300 max-w-md">
          Passionate web developer focused on building modern web apps using
          React, Next.js and Tailwind CSS 🚀
        </p>
      </div>

      {/* Info Section */}
      <div className="grid md:grid-cols-2 gap-6">
        <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow">
          <h3 className="text-lg font-semibold mb-4 text-gray-900 dark:text-white">
            Personal Info
          </h3>

          <p className="text-gray-600 dark:text-gray-300 mb-2">
            📧 Email: saharier@example.com
          </p>
          <p className="text-gray-600 dark:text-gray-300 mb-2">
            📍 Location: Bangladesh
          </p>
          <p className="text-gray-600 dark:text-gray-300">
            🌐 Website: myportfolio.com
          </p>
        </div>

        <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow">
          <h3 className="text-lg font-semibold mb-4 text-gray-900 dark:text-white">
            Skills
          </h3>

          <div className="flex flex-wrap gap-2">
            <span className="bg-yellow-400 text-black px-3 py-1 rounded-full text-sm">
              React
            </span>
            <span className="bg-yellow-400 text-black px-3 py-1 rounded-full text-sm">
              Next.js
            </span>
            <span className="bg-yellow-400 text-black px-3 py-1 rounded-full text-sm">
              Tailwind CSS
            </span>
            <span className="bg-yellow-400 text-black px-3 py-1 rounded-full text-sm">
              JavaScript
            </span>
          </div>
        </div>
      </div>

      {/* Action Button */}
      <div className="mt-6 text-center">
        <Link href={"/editProfile"} className="bg-yellow-400 hover:bg-yellow-500 text-black px-6 py-2 rounded-lg font-semibold">
          Edit Profile
        </Link>
      </div>
    </div>
  );
};

export default ProfilePage;
