export const metadata = {
  title: "Dev Dairy - Revenue",
  description: "Generated by create next app",
};

const RevenuePage = () => {
  return (
    <div className="w-full max-w-6xl mx-auto">
      {/* Header */}
      <div className="mb-6">
        <h2 className="text-3xl font-bold text-gray-900 dark:text-white">
          Revenue 💰
        </h2>
        <p className="text-gray-500">Track your earnings and performance</p>
      </div>

      {/* Revenue Cards */}
      <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3 mb-8">
        <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow">
          <h3 className="text-sm text-gray-500">Total Revenue</h3>
          <p className="text-3xl font-bold text-gray-900 dark:text-white">
            $12,400
          </p>
        </div>

        <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow">
          <h3 className="text-sm text-gray-500">This Month</h3>
          <p className="text-3xl font-bold text-gray-900 dark:text-white">
            $2,150
          </p>
        </div>

        <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow">
          <h3 className="text-sm text-gray-500">Last Month</h3>
          <p className="text-3xl font-bold text-gray-900 dark:text-white">
            $1,980
          </p>
        </div>
      </div>

      {/* Revenue Details */}
      <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow mb-8">
        <h3 className="text-xl font-semibold mb-4 text-gray-900 dark:text-white">
          Revenue Summary
        </h3>

        <p className="text-gray-600 dark:text-gray-300 mb-2">
          Your revenue has increased compared to last month. Keep growing your
          platform by publishing more content and engaging users 🚀
        </p>

        <p className="text-gray-500 text-sm">
          Tip: Focus on high-quality blogs to increase traffic and monetization.
        </p>
      </div>

      {/* Table */}
      <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow">
        <h3 className="text-xl font-semibold mb-4 text-gray-900 dark:text-white">
          Recent Transactions
        </h3>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm text-gray-600 dark:text-gray-300">
            <thead className="border-b border-gray-200 dark:border-gray-700">
              <tr>
                <th className="py-2">Date</th>
                <th className="py-2">Source</th>
                <th className="py-2">Amount</th>
                <th className="py-2">Status</th>
              </tr>
            </thead>

            <tbody>
              <tr className="border-b border-gray-100 dark:border-gray-700">
                <td className="py-2">Apr 10</td>
                <td>Ad Revenue</td>
                <td>$120</td>
                <td className="text-green-500">Completed</td>
              </tr>

              <tr className="border-b border-gray-100 dark:border-gray-700">
                <td className="py-2">Apr 08</td>
                <td>Subscription</td>
                <td>$80</td>
                <td className="text-green-500">Completed</td>
              </tr>

              <tr>
                <td className="py-2">Apr 05</td>
                <td>Sponsorship</td>
                <td>$200</td>
                <td className="text-yellow-500">Pending</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default RevenuePage;
